"""Initial migration

Revision ID: 1d8e2f5420ce
Revises: 
Create Date: 2025-03-10 00:15:12.341792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8e2f5420ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='장비명'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='장비 분류(firewall, proxy, ips 등)'),
    sa.Column('manufacturer', sa.String(length=50), nullable=True, comment='제조사'),
    sa.Column('model', sa.String(length=50), nullable=True, comment='모델명'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='버전 정보'),
    sa.Column('ip_address', sa.String(length=100), nullable=False, comment='IP 주소'),
    sa.Column('port', sa.Integer(), nullable=True, comment='접속 포트'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='접속 계정'),
    sa.Column('password', sa.String(length=200), nullable=False, comment='접속 비밀번호'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
