"""Create device table

Revision ID: 4cb48fc8419a
Revises: 
Create Date: 2025-03-08 00:10:55.051647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4cb48fc8419a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_configs')
    op.drop_table('devices')
    op.drop_table('device_check_logs')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False, comment='장비 분류(firewall, proxy, ips 등)'))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=50), nullable=False, comment='제조사'))
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=False, comment='모델명'))
        batch_op.add_column(sa.Column('version', sa.String(length=50), nullable=True, comment='버전 정보'))
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=True, comment='접속 포트'))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False, comment='접속 계정'))
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False, comment='접속 비밀번호'))
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('last_checked')
        batch_op.drop_column('status')
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_checked', sa.DATETIME(), nullable=True))
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('port')
        batch_op.drop_column('version')
        batch_op.drop_column('model')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('category')

    op.create_table('device_check_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=False),
    sa.Column('check_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=15), nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('vendor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('properties', sqlite.JSON(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_check_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_check_message', sa.TEXT(), nullable=True),
    sa.Column('last_check_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('device_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=False),
    sa.Column('config_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
