"""Initial migration

Revision ID: 5b04fc924f50
Revises: 
Create Date: 2025-03-25 00:09:20.377514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b04fc924f50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('current_task')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_task', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
