"""Add sub_category field to Device model

Revision ID: c6c0c885bef6
Revises: 
Create Date: 2025-03-10 13:30:32.178797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c0c885bef6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='장비명'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='장비 분류(firewall)'),
    sa.Column('sub_category', sa.String(length=20), nullable=False, comment='세부 분류(paloalto, mf2, ngf, mock)'),
    sa.Column('manufacturer', sa.String(length=50), nullable=True, comment='제조사'),
    sa.Column('model', sa.String(length=50), nullable=True, comment='모델명'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='버전 정보'),
    sa.Column('ip_address', sa.String(length=100), nullable=False, comment='IP 주소'),
    sa.Column('port', sa.Integer(), nullable=True, comment='접속 포트'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='접속 계정'),
    sa.Column('password', sa.String(length=200), nullable=False, comment='접속 비밀번호'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
